apiVersion: v1
kind: Secret

metadata:
  name: blog-secret
  namespace: blog

type: Opaque

stringData:
  POSTGRES_USER: phandat_admin
  POSTGRES_PASSWORD: MatKhauSieuBaoMat2026

  DB_USER: phandat_admin
  DB_PASSWORD: MatKhauSieuBaoMat2026
